Project grocery_server_db {
  database_type: 'SQLite'
  Note: 'This will store users, grocery lists and items'
}


Table users {
    id varchar [pk]
    group varchar [ref: > groups.id]
    username varchar
    email varchar
    joinTime timestamp
}

Table categories {
    categoryId varchar [pk]
    groupId varchar [ref: > groups.id, null]
    categoryName varchar
    Note {
        '''Category names don't need to be unique, only within a group
        This prevents other groups from deleting your custom categories'''
    }
}

Table grocery_lists {
    id varchar [pk]
    groupId varchar [ref: > groups.id]
    creationTime timestamp
}

Table grocery_list_items {
    listId varchar [ref: > grocery_lists.id]
    itemId varchar [ref: > items.id]
    quantity int
}

Table items {
    id varchar [pk]
    itemName varchar
    categoryId varchar [ref: > categories.categoryId]
    creationTime timestamp
    lastUsed timestamp
}

Table groups {
    id varchar
    name varchar
    owner varchar [ref: - users.id]
    creationTime timestamp
}

Table invites {
    userId varchar [ref: > users.id]
    groupId varchar [ref: > groups.id]
    createdAt timestamp
    expirationTime timestamp
}